# Generated by Django 5.0 on 2023-12-16 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('yosh', models.IntegerField(max_length=5)),
                ('manzil', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message="1 balldan kam baho qo'yish mumkin emas"), django.core.validators.MaxValueValidator(5, message="5 baldan katta baho qo'yish mumkin emas")])),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.fan')),
                ('ism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baho.talaba')),
            ],
        ),
    ]
